### ISSUE TITLE
Documentation: CI jobs examples

### ISSUE THREAD

**Issue by yyynnn** [doczjs/docz#857]
## Question

**Description**
Is there some nicer ways to build docz in a CI tool (e.g. Travis)?
Would be cool to see some config examples in the docs. Or maybe in a form of a plugin (semantic-release etc)

p.s. great lib

**Comment by draperunner** [comment]
I am using CircleCI to deploy my docz project to Firebase Hosting.

Example `.circleci/config.yml`:

```
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/docs

    steps:
      - checkout

      - run: npm ci

      - run: npm run build

      - run: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
```

The `npm run build` is just `docz build`.

Firebase Hosting is configured to use `.docz/dist` as the "public" folder to deploy.

The Firebase token can be generated with `firebase login:ci` (https://firebase.google.com/docs/cli#admin-commands). You should save the token as an environment variable on your CircleCI server.

Next steps could be to automatically deploy your docz site when the master branch is changed. This is easy with CircleCI workflows.

Maybe the [docz-website repo](https://github.com/pedronauck/docz-website/issues) is a better suited place for this issue.

Since there is already a [Netlify tutorial](https://www.docz.site/docs/deploying-your-docs#using-netlify) in the docs, maybe there's also room for Firebase Hosting and CircleCI tutorials as well. I might make a PR for that, if I have the time.
